# Generated by Django 5.1 on 2024-08-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_vakansii', models.CharField(max_length=200, verbose_name='Nazvanie Vakansii')),
                ('imya', models.CharField(max_length=50, verbose_name='Imya')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('otchestvo', models.CharField(blank=True, max_length=50, verbose_name='Otchestvo')),
                ('data_rozhdeniya', models.DateField(verbose_name='Data Rozhdeniya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('navyki', models.TextField(verbose_name='Navyki')),
                ('opyt', models.TextField(verbose_name='Opyt')),
                ('obrazovanie', models.TextField(verbose_name='Obrazovanie')),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=200, verbose_name='Nazvanie')),
                ('nazvanie_kompanii', models.CharField(max_length=200, verbose_name='Nazvanie Kompanii')),
                ('zarplata', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zarplata')),
                ('trebovanie_navyki', models.TextField(verbose_name='Trebovanie Navyki')),
                ('obyazannosti', models.TextField(verbose_name='Obyazannosti')),
                ('adres', models.CharField(max_length=300, verbose_name='Adres')),
                ('rabotodatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
